myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp.views import *
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('createpro/', Create_product.as_view(),name='image_create'),
    path('detail/<str:pk>/', views.product_detail, name='photo'),
    path('', Home.as_view(),name='home'),
    path('promotions', Promotions.as_view(),name='promotions'),
    path('type', views.type_view,name='type'),
    path('help', Report.as_view(),name='help'),
    path('logout/',customerlogoutView.as_view(),name='customerlogout'),
    path('login', customerloginView.as_view(), name="customerlogin"),
    path('profile/',views.profile, name='profile'),
    path('cart/',views.cart, name='cart'),

    path('add/',views.add_to_cart, name='add'),
    path('addon/',views.add_cart, name='addon'),
    path('removeon/',views.remove_cart, name='removeon'),

    path('createprofile/',CreateProfile.as_view(), name='createprofile'),

    path('transaction', views.transactionview, name='transaction'),
    path('detail_transaction/<tran>', views.detail_transaction, name='detail_transaction'),

    path('qr_mobile/<mobile>/<amount>/qr.png', views.get_qr, name='qr'),
    path('qr_nid/<nid>/<amount>/', views.get_qr, name='qr'),
    path('ct', views.createTransaction, name='ct'),

    path('accounts/', include('allauth.urls')),
    path('register/', customerregistrationView.as_view(), name="customerregistration")
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from pyexpat import model
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

class Product_list(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=1000, null=True, blank=True)
    type_product = models.CharField(max_length=50)
    price = models.IntegerField()
    image=models.ImageField(upload_to='product_images')
    def __str__(self):
        return "%s"%(self.name)

class customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,default=None)
    email = models.EmailField()
    name = models.CharField(max_length=30)
    phone = models.CharField(max_length=11, blank=True)
    surname = models.CharField(max_length=30)
    gender = models.CharField(max_length=1, default="N")
    country = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

class Transaction(models.Model):
    customer = models.ForeignKey(customer, on_delete=models.SET_NULL, default=None, blank=True, null=True)
    transaction = models.CharField(max_length=50)
    total = models.PositiveIntegerField(default=0)
    stats = models.PositiveIntegerField(default=0)
    image = models.ImageField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.transaction

class Order(models.Model):
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    product = models.ForeignKey(Product_list, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self) -> str:
        return "ID:%s Quantity: %s name: %s"%(self.transaction, self.quantity, self.product)

class Report_issue(models.Model):
    email = models.CharField(max_length=100)
    problem = models.CharField(max_length=200)
    product_id = models.CharField(max_length=10)
    info = models.CharField(max_length=1000)

    def __str__(self):
        return self.problem

myapp/views.py
from dataclasses import dataclass
from statistics import median
from django.shortcuts import render, redirect
from myapp.models import *
from django.views.generic.edit import CreateView
from django.views.generic import ListView, View, FormView
from django.urls import reverse
from django.contrib.auth.models import User
from myapp.forms import *
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_object_or_404, redirect
import json
import random

class Create_product(CreateView):
    model = Product_list
    template_name = 'image_create.html'
    fields = ['image', 'name', 'description', 'type_product', 'price']

    def get_success_url(self):
        return reverse('home')


class Home(ListView):
    model = Product_list
    template_name = 'home.html'


class Promotions(ListView):
    model = Product_list
    template_name = 'promotions.html'

def transactionview(request):
    user = request.user.customer
    transaction = Transaction.objects.filter(customer=user)
    title_image = []
    for i in transaction:
        title_image.append(Order.objects.filter(transaction=i)[0])
    
    transaction = zip(transaction, title_image)
    context = {
        "items": transaction
    }
    return render(request, 'transaction.html', context)

def detail_transaction(request, tran):
    user = request.user.customer
    tran = Transaction.objects.get(transaction=tran)
    list_product = Order.objects.filter(transaction_id=tran)
    total_price = []
    for i in list_product:
        total_price.append(i.quantity * i.product.price)
    print(total_price)
    list_product = zip(list_product ,total_price)
    context = {
        "items": list_product
    }
    return render(request, "list_order.html", context)

def type_view(request):
    soft = Product_list.objects.filter(type_product='low')
    medium = Product_list.objects.filter(type_product='medium')
    hight = Product_list.objects.filter(type_product='hight')
    print(soft)
    context = {
        'soft': soft,
        "medium": medium,
        "hight": hight
    }
    return render(request, 'type.html', context)

def cart (request):
    list_item = []
    info_item = [[],[]]
    hash = (random.getrandbits(128))
    transaction = ("%010x" % hash)
    form = Createtransaction(request.POST or None)

    if request.method == 'POST':
        form = Createtransaction(request.POST, request.FILE)
        if form.is_valid():
            form.save
    try:
        data = json.loads(request.COOKIES.get('cart'))['data']

        for d in data:
            print(d['name'],'D')
            list_item.append(d['name'])
            info_item[0].append((d['total_price']))
            info_item[1].append(d['quantity'])
            
    except:
        data = []
    print(list_item,':D')
    print(info_item,'info')
    print(data)
    # items = Product_list.objects.filter(name__in = list_item)
    items = list(map(lambda name: Product_list.objects.get(name=name), list_item))

    print(items,':D')
    items = zip(items, info_item[0], info_item[1])
    context = {
        'items': items, 
        'total': info_item[0],
        'price_total': sum(info_item[0]),
        "mobile":"0863624849",
        "amount": float(sum(info_item[0])),
        "form":form}
    return render(request, 'cart.html', context)

def createTransaction (request):
    data = json.loads(request.COOKIES.get('cart'))['data']
    customer = request.user.customer
    hash = (random.getrandbits(128))
    transaction = ("%010x" % hash)[0:20]
    print(transaction)
    print(customer)
    total_price = 0
    transac, created = Transaction.objects.get_or_create(
    customer=customer, transaction=transaction,
    stats=0)
    transaction = Transaction.objects.get(transaction = transaction)
    for i in data:
        product = Product_list.objects.get(name=i['name'])
        Order.objects.create(transaction=transaction, product=product,
        quantity=i['quantity'])
        total_price += i['total_price']
    transac.total = total_price
    transac.save()

    dictionary = {"data": []}
    json_object = json.dumps(dictionary, indent = 4)
    print(json_object)
    response = redirect('transaction')
    response.set_cookie('cart', json_object)
    return response


class Report(CreateView):
    template_name = 'help.html'
    form_class = Report_Problem
    success_url = reverse_lazy('home')


    def get_success_url(self):
        return reverse('home')


def profile(request):
    try:
        instance = get_object_or_404(customer, user=request.user)
        form = ProfileForm(request.POST or None, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            context = {
                'form': form,
                'user': request.user
            }
            return render(request, 'profile.html', context)
    except:
        return redirect('createprofile')

class customerlogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('home')


def product_detail(request, pk):
    photo = Product_list.objects.get(id=pk)
    print(photo,':D')
    recom = Product_list.objects.all()
    return render(request, 'product_detail.html', {'photo': photo, "rec":recom[0:4]})


data = []
def add_to_cart(request):
    global data
    try:
        data = json.loads(request.COOKIES.get('cart'))['data']
    except:
        pass
    print(data)
    name = request.POST.get("name", "")
    price = int(request.POST.get("price", ""))
    myitem={
        "name": name,
        "price": price,
        "total_price": price,
        "quantity": 1
        }
    
    for num, d in enumerate(data):
        if (d['name'] == name):
            data[num]['quantity'] += 1
            data[num]['total_price'] += price
            break
    else:
        data += [myitem,]
    dictionary = {"data": data}
    json_object = json.dumps(dictionary, indent = 4)
    print(json_object)
    response = redirect('home')
    response.set_cookie('cart', json_object)
    return response

def add_cart(request):
    global data
    try:
        data = json.loads(request.COOKIES.get('cart'))['data']
    except:
        pass
    print(data)
    name = request.POST.get("name", "")
    price = int(request.POST.get("price", ""))
    myitem={
        "name": name,
        "price": price,
        "total_price": price,
        "quantity": 1
        }
    
    print(myitem, 'check add\n\n')
    for num, d in enumerate(data):
        if (d['name'] == name):
            data[num]['quantity'] += 1
            data[num]['total_price'] += price
            break
    else:
        data += [myitem,]
    dictionary = {"data": data}
    json_object = json.dumps(dictionary, indent = 4)
    print(json_object)
    response = redirect('cart')
    response.set_cookie('cart', json_object)
    return response

def remove_cart(request):
    global data
    try:
        data = json.loads(request.COOKIES.get('cart'))['data']
    except:
        pass
    print(data)
    name = request.POST.get("name", "")
    price = int(request.POST.get("price", ""))
    myitem={
        "name": name,
        "price": price,
        "total_price": price,
        "quantity": 1
        }
    
    for num, d in enumerate(data):
        if (d['quantity'] == 1):
            del data[num]
            break
        elif (d['name'] == name):
            data[num]['quantity'] -= 1
            data[num]['total_price'] -= price
            break
    else:
        data += [myitem,]
    dictionary = {"data": data}
    json_object = json.dumps(dictionary, indent = 4)
    print(json_object)
    response = redirect('cart')
    response.set_cookie('cart', json_object)
    return response
 

class customerloginView(FormView):
    template_name = 'login.html'
    form_class = customerloginForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data["password"]
        usr = authenticate(username=username, password=password)
        if usr is not None and customer.objects.filter(user=usr).exists():
            login(self.request, usr)
        else:
            return render(self.request, self.template_name, {"form": self.form_class, "error": "Invalid credentials"})
        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url


class CreateProfile(CreateView):
    template_name = 'profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('home')

class customerregistrationView(CreateView):
    template_name = 'register.html'
    form_class = customerregistrationForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        email = form.cleaned_data.get('email')
        user = User.objects.create_user(username, email, password)
        form.instance.user = user
        login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('home')


from django.http import HttpResponse
from PIL import Image
import libscrc
import qrcode


def calculate_crc(code):
    crc = libscrc.ccitt_false(str.encode(code))
    crc = str(hex(crc))
    crc = crc[2:].upper()
    return crc.rjust(4, '0')

def gen_code(mobile="", nid="", amount=1.23):
    code="00020101021153037645802TH29370016A000000677010111"
    if mobile:
        tag,value = 1,"0066"+mobile[1:]

myapp/templates/cart.html
{% load static %}
{% load crispy_forms_tags %}

<style>


    body{
        background: radial-gradient(ellipse at center,#192d38 0,#211f2f 100%);
    }
    .con {
        display: flex;
        margin: 0% 15%;
        border-radius: 10px;
        flex-direction: column;
        justify-content: flex-start;
        background-color: #E2E2E2;
    }

    .con_img {
        margin: 35px;
        display: flex;
        width: 400px;
        border-radius: 10px;
        background-color: #F0F0F0;
    }

    .con_img img {
        width: 400px;
    }

    .con_info {
        display: flex;
        flex-direction: column;
        border-radius: 10px;
        background-color: #E2E2E2;
    }

    .con_text {
        display: flex;
        margin: 10px;
        padding-left: 15px;
        padding-right: 15px;
        border-radius: 10px;
        background-color: #ffffff;
    }

    .info {
        word-wrap: break-word;
        max-width: 500px;
        hyphens: auto;
    }

    .contro {
        margin: 10px 400px 10px 10px;
        padding-left: 15px;
        padding-right: 15px;
        border-radius: 10px;
        background-color: #ffffff;
    }

    .image {
        position: relative;
        margin: auto;
    }

    .name_info {
        display: flex;
    }

    .column {
        /* display: flex; */
        max-width: 15%;
    }

    .column img {
        border-radius: 10px;
        vertical-align: middle;
        width: 50%;
    }

    .column:hover .image {
        opacity: 0.5;
    }


    .parent_main {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        grid-template-rows: 1fr;
        grid-column-gap: 5px;
        grid-row-gap: 0px;
    }

    .div1_main {
        grid-area: 1 / 1 / 2 / 3;
    }

    .div2_main {
        grid-area: 1 / 3 / 2 / 4;
        position: relative;
        display: flex;
        flex-direction: column;
        margin: auto;
    }

    .div2_main a {
        float: left;
        display: block;
        color: #A7D8D5;
        background: #417E77;
        text-align: center;
        padding: 10px 70px;
        border-radius: 5px;
        text-decoration: none;
        font-size: 20px;
    }

    .parent {
        background-color: #A7D8D5;
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-bottom-left-radius: 10px;
        border-top-left-radius: 10px;
        grid-template-rows: 1fr;
        grid-column-gap: 5px;
        grid-row-gap: 0px;
        margin-left: 15px;
        margin-top: 15px;
        height: 150px;
    }

    .div1 {
        grid-area: 1 / 1 / 3 / 2;
        display: flex;
        justify-content: center;
        background-color: aliceblue;
        margin: 5px;
        border-radius: 10px;
    }

    .div2 {
        grid-area: 1 / 2 / 2 / 3;
        position: relative;
        margin: auto;
        margin-left: 0px;
    }

    .div3 {
        grid-area: 1 / 3 / 2 / 4;
        display: flex;
        margin: auto;
    }

    .div3 button {
        background: none;
        border: none;
        color: #417e77;
        font-size: 20px;
    }


    .div3 button:hover {
        color: #6ab9b0;
    }

    .div4 {
        grid-area: 1 / 4 / 2 / 5;
        position: relative;
        margin: auto;
    }

    .item_scroll {
        background-color: #6ab9b0;
        border-bottom-left-radius: 10px;
        height: 510px;
        overflow: auto;
    }

    .con_select {
        display: flex;
        margin: 0% 15%;
        border-radius: 10px;
        padding-bottom: 20px;

        max-width: 100%;

        justify-content: space-around;
        margin-top: 140px;
        margin-bottom: -20px;
        background-color: #417e77;
    }

    .con_select a {
        float: left;
        display: block;
        color: #A7D8D5;
        background: #417E77;
        text-align: center;
        padding: 10px;
        width: 100%;
        text-decoration: none;
        font-size: 20px;
    }

    .con_select a:hover {
        background: #58a199;
        color: #000000;
    }

    .con_select a.active {
        background: #58a199;
        color: #000000;
    }

    .parent_ {
        display: grid;
        grid-template-columns: 1fr;
        grid-template-rows: repeat(4, 1fr);
        grid-column-gap: 0px;
        grid-row-gap: 0px;
    }
</style>

<head>
    <script src="https://kit.fontawesome.com/e344495af0.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href='{% static "css/cart.css" %}'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display+SC:wght@700&display=swap" rel="stylesheet">
</head>

<body>



    <div class="con_select">
        <a class="active">Sipping Cart</a>
        <a href="{% url 'transaction' %}">purchase history</a>
    </div>

    </div>
    <div class="con">
        {% if price_total != 0 %}
        <div class="parent_main">
            <div class="div1_main">
                <div class="item_scroll">
                    {% for item, total, quantity in items %}
                    <div class="parent">

                        <div class="div1"><img src="{{item.image.url}}" class="image" style="height:100%"></div>
                        <div class="div2">
                            <h3>{{item.name}}</h2>
                                <h3 style="margin-top: -25px;">{{item.price}} bath</h3>
                        </div>
                        <div class="div3">
                            <form action="{% url 'removeon' %}" method="post" style="margin: auto;">
                                {% csrf_token %}
                                <input type="hidden" name="name" value="{{item.name}}">
                                <input type="hidden" name="price" value="{{item.price}}">
                                <button class="fa-solid fa-circle-minus" type="submit"></button>
                            </form>
                            <h3 style="padding: 10px">{{quantity}}</h3>
                            <form action="{% url 'addon' %}" method="post" style="margin: auto;">
                                {% csrf_token %}
                                <input type="hidden" name="name" value="{{item.name}}">
                                <input type="hidden" name="price" value="{{item.price}}">
                                <button class="fa-solid fa-circle-plus" type="submit"></button>
                            </form>
                        </div>
                        <div class="div4">
                            <h3>{{total}} bath</h2>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="div2_main">
                <img src="{% url 'qr' mobile=mobile amount=amount %}">
                <h2>Total {{price_total}}</h2>
                {% if transac == 0 %}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" id="myfile" name="myfile"><br><br>
                    <input type="submit" value="Upload">
                </form>
                <a>Please Upload Slip</a>
                {% else %}
                <a href="{% url 'ct' %}">Check out</a>
                {% endif %}
            </div>
        </div>
        {% else %}
        <h1 style="position: relative; margin: auto; padding: 10%;">Shoping cart is empty</h1>
        {% endif %}
    </div>

    <div style="position: fixed; width: 100%; top: 0px;">
        <div class="logo">

            <img src="{% static 'media\logo.png' %}" width="200px">
            <div class="login">

                <a id="botton" class="fa-solid fa-basket-shopping"
                    style="font-size: 28; margin: 6px 3px; background: none;"></a>
                {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="dropbtn">{{user.username}}</button>
                    <div class="dropdown-content">
                        <a href="{% url 'profile' %}">PROFILE</a>
                        <a href="{% url 'customerlogout' %}">Logout</a>
                    </div>
                </div>
                {% else %}
                <a id="botton" href="{% url 'customerregistration' %}">Sign up</a>
                <a id="botton" href="{% url 'customerlogin' %}">Sign in</a>
                {% endif %}
            </div>
        </div>
        <div class="navbar">
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'promotions' %}">Promotions</a>
            <a href="{% url 'type' %}">Type</a>
            <a href="{% url 'help' %}">Help</a>
        </div>
    </div>

</body>

</html>

myapp/templates/help.html
{% load static %}
{% load crispy_forms_tags %}


<head>
    <script src="https://kit.fontawesome.com/e344495af0.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href='{% static "css/style.css" %}'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display+SC:wght@700&display=swap" rel="stylesheet">
</head>

<body>


    <div style="position: fixed; width: 100%; top: 0px;">
        <div class="logo">

            <img src="{% static 'media\logo.png' %}" width="200px">
            <div class="login">

                <a href="{% url 'cart' %}" id="botton" class="fa-solid fa-basket-shopping"
                    style="font-size: 28; margin: 6px 3px; background: none;"></a>
                {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="dropbtn">{{user.username}}</button>
                    <div class="dropdown-content">
                        <a href="{% url 'profile' %}">PROFILE</a>
                        <a href="{% url 'customerlogout' %}">Logout</a>
                    </div>
                </div>
                {% else %}
                <a id="botton" href="{% url 'customerregistration' %}">Sign up</a>
                <a id="botton" href="{% url 'customerlogin' %}">Sign in</a>
                {% endif %}
            </div>
        </div>
        <div class="navbar">
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'promotions' %}">Promotions</a>
            <a href="{% url 'type' %}">Type</a>
            <a class="active" href="#">Help</a>
        </div>
    </div>


    {% block content %}
    <form method="post">
        {% csrf_token %}
        <h2 style="margin-top: 145px; text-align: center;">Help and Support</h2>
        <div class="con">
            <div class="con_input">
                {{ form.email|as_crispy_field }}
                {{ form.problem|as_crispy_field }}
                {{ form.product_id|as_crispy_field }}
                <textarea type="text" name="info" style="background-color: #417E77;"
                    class="textinput textInput form-control" required="" id="id_info"></textarea>
                <button type="submit" id="submit">Sent</button>
            </div>
        </div>
    </form>
    {% endblock %}
</body>

myapp/templates/home.html
{% load static %}
<style>
    /* @media screen and (max-width: 1408px) {
        .container {
    display: block;
    box-sizing: border-box;
    margin: 20px 60px;
    }
}
    @media screen and (max-width: 1328px) {
        .container {
    display: block;
    box-sizing: border-box;
    margin: 20px 30px;
    }
}
    @media screen and (max-width: 1268px) {
        .container {
    display: block;
    box-sizing: border-box;
    margin: 20px 1px;
    }
}
    @media screen and (max-width: 1210px) {
        .container {
    display: block;
    box-sizing: border-box;
    margin: 20px -35px;
    }
}
    @media screen and (max-width: 1001px) {
        .container {
    display: block;
    box-sizing: border-box;
    margin: 20px -115px;
    }
}
@media screen and (max-width: 400px) {
        .container {
    display: block;
    box-sizing: border-box;
    margin: 20px -150px;
    }
} */
</style>

<head>
    <script src="https://kit.fontawesome.com/e344495af0.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href='{% static "css/style.css" %}'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display+SC:wght@700&display=swap" rel="stylesheet">
</head>

<body>


    <div style="position: fixed; width: 100%;">
        <div class="logo">

            <img src="{% static 'media\logo.png' %}" width="200px">
            <div class="login">

                <a href="{% url 'cart' %}" id="botton" class="fa-solid fa-basket-shopping"
                    style="font-size: 28; margin: 6px 3px; background: none;"></a>
                {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="dropbtn">{{user.username}}</button>
                    <div class="dropdown-content">
                        <a href="{% url 'profile' %}">PROFILE</a>
                        <a href="{% url 'customerlogout' %}">Logout</a>
                    </div>
                </div>
                {% else %}
                <a id="botton" href="{% url 'customerregistration' %}">Sign up</a>
                <a id="botton" href="{% url 'customerlogin' %}">Sign in</a>
                {% endif %}
            </div>
        </div>
        <div class="navbar">
            <a class="active" href="#home">Home</a>
            <a href="{% url 'promotions' %}">Promotions</a>
            <a href="{% url 'type' %}">Type</a>
            <a href="{% url 'help' %}">Help</a>
        </div>
    </div>


    <h1 style="padding-top: 150px; text-align: center;    font-size: 45px">What's new</h1>
    <img class="center" style="box-shadow: 11px 0px 43px 0px rgb(0 74 77);margin-top: 35px;"
        src="{% static 'media\promotion.jpg' %}">

    <h2 style="text-align: center;font-size: 45px;">Product list</h1>
        <div class="container">
            <div class="row">
                {% for i in object_list %}
                <div class="column">
                    <a href="{% url 'photo' i.id %}"><img src="{{i.image.url}}" class="image" style="width:100%"></a>
                    <p class="nameitem">{{i.name}}
                    </p>
                </div>
                {% endfor %}
            </div>
        </div>
</body>

myapp/templates/login.html
{% load account socialaccount %}
{% load static %}
{% load crispy_forms_tags %}


<head>
    <script src="https://kit.fontawesome.com/e344495af0.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href='{% static "css/login.css" %}'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display+SC:wght@700&display=swap" rel="stylesheet">
</head>

<body>

    <div style="position: fixed; width: 100%; top: 0px;">
        <div class="logo">

            <img src="{% static 'media\logo.png' %}" width="200px">
            <div class="login">

                <a href="{% url 'cart' %}" id="botton" class="fa-solid fa-basket-shopping" style="font-size: 28; margin: 6px 3px; background: none;"></a>
                {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="dropbtn">{{user.username}}</button>
                    <div class="dropdown-content">
                        <a href="{% url 'profile' %}">PROFILE</a>
                        <a href="{% url 'customerlogout' %}">Logout</a>
                    </div>
                </div>
                {% else %}
                <a id="botton" href="{% url 'customerregistration' %}">Sign up</a>
                <a id="botton" href="{% url 'customerlogin' %}">Sign in</a>
                {% endif %}
            </div>
        </div>
        <div class="navbar">
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'promotions' %}">Promotions</a>
            <a href="{% url 'type' %}">Type</a>
            <a href="{% url 'help' %}">Help</a>
        </div>
    </div>


    {% block content %}
    <form method="post">
        {% csrf_token %}
        <h2 style="margin-top: 145px; text-align: center;">Sign in</h2>
        <div class="containerF">

            <div style="margin: 20px 15px;">
                <div class="forms">
                    {{ form.username|as_crispy_field }}
                    {{ form.password|as_crispy_field }}
                </div>
                <div class="bot">
                    <button type="submit" id="submit">Login</button>
                    <a style="background-color: #a7d8d5;" href="{% provider_login_url 'google' %}">Login with Google</a>
                </div>
            </div>
        </div>
    </form>
    {% endblock %}

    {% if error %}
    <li style="color:red">{{error}}</li>
    {% endif %}

</body>